### ISSUE TITLE
Consistency with nu and nu_post, nu_pre

### ISSUE THREAD

**Issue by sharath** [Hananel-Hazan/bindsnet#156]
There are some inconsistencies with nu_post and nu_pre. For instance, the Network is implemented using a tuple (nu_pre, nu_post) whereas some of the models use nu_pre, nu_post as separate parameters. (Also since they have kwargs it silently does nothing if one is used instead of the other)

I think we should try to keep it consistent.

Unless this is intentional?

**Comment by djsaunde** [comment]
Yeah, I think this makes sense. The reason for the inconsistency is because both used to use `nu_pre, nu_post`, and I recently switched the `topology` modules and `LearningRule`s (I think this is what you meant by `Network`?) use `nu`. I simply hadn't switched them yet, since the `models` are pretty low priority / are there for our own experimental convenience.
