### ISSUE TITLE
How to reproduce the SOM SNN work

### ISSUE THREAD

**Issue by rachmadvwp** [Hananel-Hazan/bindsnet#235]
Hi,
I'm interested on reproducing the SOM SNN work "Unsupervised Learning with Self-Organizing Spiking Neural Networks" https://doi.org/10.1109/IJCNN.2018.8489673. I'd like to know if the bindsnet already includes the codes to reproduce this work. If not, could you provide hints how to do that. 
Apart from that, I'd like to ensure something since I'm new to python, i.e., if I'd like to do "test" right after "training", I just need to disable the train option right or should I do other things? 
Thanks and best regards.

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

We wrote our code for that paper in [the BRIAN simulator](https://github.com/brian-team/brian2), which can be found [here](https://github.com/djsaunde/lm-snn). It's quite disorganized, though.

Something similar, however, can be found [in the BindsNET experiments repo](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/increasing_inhibition.py). It might need some tweaking in order to work correctly.

In BindsNET, for the test phase, you can set `network.learning = False` to disable updates by `LearningRule`s. But, you may also want to freeze thresholds on neurons with adaptive thresholds. E.g., before we added the `network.learning` flag, [here](https://github.com/djsaunde/bindsnet_experiments/blob/3c06d346ded360173a7f94bd84d6fa01312316f8/experiments/mnist/increasing_inhibition.py#L99) I created a no-op learning rule in place of the old STDP rule, and set the adaptive threshold parameters of the `DiehlAndCookNodes` to 0.

**Comment by Hananel-Hazan** [comment]
Hi @rachmadvwp 

Try to look on the `class IncreasingInhibitionNetwork(Network)` from [here](https://github.com/Hananel-Hazan/bindsnet/blob/cc45e290529b39db5050a9798ac849da140c8479/bindsnet/models/__init__.py#L165)

**Comment by rachmadvwp** [comment]
Hi @djsaunde 

I'm sorry but I'm still not clear with the steps.
Are you saying that by setting `network.learning = False`, the simulation will be doing "training" and followed by "test" subsequently? Or I have to do separate things, "training" first, save the models in some files (freezing the parameters) and read it back for "test" phase?
 
Is `network.learning = False` the one in the [bindsnet\network\__init__.py](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/network/__init__.py) ?

Another question is that, how can I use the BindsNET experiments repo along with the BindsNET framework? Should I do some additional setting or just treat the experiments repo like examples folder?

Thanks for the answers and helps.
Best regards.
