### ISSUE TITLE
 decay neuron's voltage in every time step

### ISSUE THREAD

**Issue by ati6868** [Hananel-Hazan/bindsnet#322]
why we have to decay neuron's voltage in every time step??
could you please tell me the reason ?

**Comment by djsaunde** [comment]
Hi @ati6868, not all neurons' voltages are decayed in each timestep (e.g., `IFNodes`, and some don't even have voltage (e.g., `McCullochPitts`). The neurons that do have decaying voltage (e.g., `LIFNodes`) do so because that is how they're defined in the literature; see, for example, [here]https://neuronaldynamics.epfl.ch/online/Ch1.S3.html).
